### ISSUE TITLE
Module with camelcase name

### ISSUE THREAD

**Issue by pirlgon** [l00ptr/ansible-collection-dolibarr#6]
I attempted to use this collection to update/install a module, but I encountered an issue with the final module control script.
The module class is modBankImportApi. Here is my YAML file:
```
- name: Upgrade a Dolibarr module
  hosts: *****
  become: true
  vars:
    dolibarr_modules:
      - name: bankimportapi
        version: master
        repo_url: ******
        activated: true
    dolibarr_domain: *****
  tasks:
    - name: Upgrade module
      import_role:
        name: l00ptr.dolibarr.install_modules
```
The name is used twice, once for the destination folder in custom and once to check the module class.
This is causing the module check to fail with the error message 'Class 'modBankimportapi' not found'.
When using `bankImportApi` in camelcase, I still receive the same error because `capitalize` does not maintain the rest of the string unchanged.
https://github.com/l00ptr/ansible-collection-dolibarr/blob/aad75587ffa14cd43f4e90832242874f00eb8b62/roles/install_modules/tasks/install_module.yml#L21

I attempted to replace it with `--module=mod{{ item.name | first | upper }}{{ item.name[1:] }}`. However, this resulted in the destination folder also being in camelcase.
